defmodule MaestroWeb.Components.RulesStatsComponent do
  @moduledoc "Stats dashboard for the rules curation page."
  use MaestroWeb, :html

  attr :bundle_stats, :list, required: true
  attr :quality_summary, :map, required: true
  attr :deps_info, :list, required: true

  @spec rules_stats(term()) :: term()
  def rules_stats(assigns) do
    assigns = assign(assigns, :max_count, max_bundle_count(assigns.bundle_stats))

    ~H"""
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-4">
      <.bundle_distribution bundle_stats={@bundle_stats} max_count={@max_count} />
      <.quality_coverage quality_summary={@quality_summary} deps_info={@deps_info} />
    </div>
    """
  end

  attr :bundle_stats, :list, required: true
  attr :max_count, :integer, required: true

  defp bundle_distribution(assigns) do
    ~H"""
    <div class="card bg-base-200">
      <div class="card-body">
        <h3>Bundle Distribution</h3>
        <div class="space-y-2">
          <%= for {bundle, count} <- @bundle_stats do %>
            <div class="flex items-center gap-3">
              <span class={["badge badge-sm w-20 justify-center", bundle_badge_class(bundle)]}>
                {bundle}
              </span>
              <progress
                class={["progress flex-1", bundle_progress_class(bundle)]}
                value={count}
                max={@max_count}
              />
              <span class="font-mono text-sm w-8 text-right">{count}</span>
            </div>
          <% end %>
        </div>
        <p class="text-xs opacity-40 mt-2">
          Agents read <code>rules.json</code> (universal) + specialized bundle.
          Generated by <code>mix maestro.rules.export</code>.
        </p>
      </div>
    </div>
    """
  end

  attr :quality_summary, :map, required: true
  attr :deps_info, :list, required: true

  defp quality_coverage(assigns) do
    ~H"""
    <div class="card bg-base-200">
      <div class="card-body">
        <h3>Quality + Coverage</h3>
        <div class="flex gap-3 mb-3">
          <span class="badge badge-success gap-1">
            Pass <span class="font-mono">{@quality_summary.pass}</span>
          </span>
          <span class="badge badge-error gap-1">
            Fail <span class="font-mono">{@quality_summary.fail}</span>
          </span>
          <span class="badge badge-outline gap-1">
            {@quality_summary.pass_rate}% pass rate
          </span>
        </div>
        <div class="overflow-x-auto max-h-48">
          <.coverage_table deps_info={@deps_info} />
        </div>
      </div>
    </div>
    """
  end

  attr :deps_info, :list, required: true

  defp coverage_table(assigns) do
    ~H"""
    <table class="table table-xs">
      <thead>
        <tr>
          <th>Source</th>
          <th class="text-center">Cov</th>
          <th class="text-center text-success">A</th>
          <th class="text-center text-warning">P</th>
          <th class="text-center text-info">L</th>
          <th class="text-center text-base-content/40">R</th>
        </tr>
      </thead>
      <tbody>
        <%= for d <- @deps_info do %>
          <tr>
            <td
              class="font-mono text-xs cursor-pointer hover:underline"
              phx-click="filter_source"
              phx-value-source={d.dep}
            >
              {d.dep}
            </td>
            <td class="text-center">
              <span class={["text-xs font-mono", coverage_color(d.coverage_pct)]}>
                {d.coverage_pct}%
              </span>
            </td>
            <td class="text-center">
              <span
                class="text-success cursor-pointer hover:underline"
                phx-click="filter_source_status"
                phx-value-source={d.dep}
                phx-value-status="approved"
              >
                {d.approved}
              </span>
            </td>
            <td class="text-center">
              <span
                class={[
                  "cursor-pointer hover:underline",
                  if(d.proposed > 0,
                    do: "text-warning font-semibold",
                    else: "text-base-content/40"
                  )
                ]}
                phx-click="filter_source_status"
                phx-value-source={d.dep}
                phx-value-status="proposed"
              >
                {d.proposed}
              </span>
            </td>
            <td class="text-center">
              <span
                class="text-info cursor-pointer hover:underline"
                phx-click="filter_source_status"
                phx-value-source={d.dep}
                phx-value-status="linter"
              >
                {d.linter}
              </span>
            </td>
            <td class="text-center">
              <span
                class="text-base-content/40 cursor-pointer hover:underline"
                phx-click="filter_source_status"
                phx-value-source={d.dep}
                phx-value-status="retired"
              >
                {d.retired}
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    """
  end

  defp bundle_badge_class("universal"), do: "badge-primary"
  defp bundle_badge_class(:universal), do: "badge-primary"
  defp bundle_badge_class("ui"), do: "badge-secondary"
  defp bundle_badge_class(:ui), do: "badge-secondary"
  defp bundle_badge_class("model"), do: "badge-accent"
  defp bundle_badge_class(:model), do: "badge-accent"
  defp bundle_badge_class("devops"), do: "badge-info"
  defp bundle_badge_class(:devops), do: "badge-info"
  defp bundle_badge_class("maestro"), do: "badge-warning"
  defp bundle_badge_class(:maestro), do: "badge-warning"
  defp bundle_badge_class(_), do: "badge-ghost"

  defp bundle_progress_class("universal"), do: "progress-primary"
  defp bundle_progress_class("model"), do: "progress-accent"
  defp bundle_progress_class("ui"), do: "progress-secondary"
  defp bundle_progress_class("devops"), do: "progress-info"
  defp bundle_progress_class("maestro"), do: "progress-warning"
  defp bundle_progress_class(_), do: ""

  defp coverage_color(pct) when pct >= 80, do: "text-success"
  defp coverage_color(pct) when pct >= 40, do: "text-warning"
  defp coverage_color(_), do: "text-error"

  defp max_bundle_count([]), do: 1
  defp max_bundle_count(stats), do: stats |> Enum.map(fn {_, c} -> c end) |> Enum.max()
end
