defmodule Mix.Tasks.Maestro.Gen.ClaudeMd do
  @moduledoc """
  Generate a CLAUDE.md file from approved rules.

  ## Usage

      # Generate for a specific project type
      mix maestro.gen.claude_md --type ash --output /path/to/project/CLAUDE.md

      # Preview what would be generated (stdout)
      mix maestro.gen.claude_md --type ash

      # Generate for all project types
      mix maestro.gen.claude_md --type all

  ## Options

    * `--type` - Project type filter: all, ash, phoenix, liveview (default: all)
    * `--output` - Write to file path instead of stdout
    * `--include-proposed` - Include proposed rules (marked as such)
  """

  use Mix.Task
  @shortdoc "Generate CLAUDE.md from approved rules"

  @spec run([String.t()]) :: :ok
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _, _} =
      OptionParser.parse(args,
        strict: [
          type: :string,
          output: :string,
          include_proposed: :boolean
        ]
      )

    project_type = opts[:type] || "all"
    include_proposed = opts[:include_proposed] || false

    rules = load_rules(project_type, include_proposed)
    content = render_claude_md(rules, project_type)

    case opts[:output] do
      nil ->
        Mix.shell().info(content)

      path ->
        File.write!(path, content)
        Mix.shell().info("Generated CLAUDE.md at #{path} (#{length(rules)} rules)")
    end
  end

  defp load_rules(project_type, include_proposed) do
    approved = Maestro.Ops.Rule.approved!()
    proposed = if include_proposed, do: Maestro.Ops.Rule.proposed!(), else: []

    (approved ++ proposed)
    |> Enum.filter(fn rule ->
      if project_type == "all" do
        true
      else
        applies = rule.applies_to || ["all"]
        "all" in applies or project_type in applies
      end
    end)
    |> Enum.sort_by(fn rule -> {severity_order(rule.severity), to_string(rule.category)} end)
  end

  defp severity_order(:must), do: 0
  defp severity_order(:should), do: 1
  defp severity_order(:prefer), do: 2

  defp render_claude_md(rules, project_type) do
    by_category = Enum.group_by(rules, & &1.category)

    rule_sections =
      by_category
      |> Enum.sort_by(fn {cat, _} -> to_string(cat) end)
      |> Enum.map(fn {category, cat_rules} ->
        rule_lines =
          cat_rules
          |> Enum.map(fn rule ->
            prefix = severity_prefix(rule.severity)
            proposed = if rule.status == :proposed, do: " [PROPOSED]", else: ""
            "#{prefix} #{rule.content}#{proposed}"
          end)
          |> Enum.join("\n\n")

        "## #{format_category(category)}\n\n#{rule_lines}"
      end)
      |> Enum.join("\n\n")

    # Load current task context
    task_context = load_task_context()

    """
    # Maestro — Agent Guidelines
    # Generated by Maestro · #{Date.utc_today()} · #{length(rules)} approved rules
    # Review and curate rules at http://localhost:4004/rules

    **Please read, acknowledge, and follow these guidelines.**
    Your first message must confirm you have read and will follow them.

    ---

    # Startup Protocol

    You MUST complete these steps BEFORE your first response. Do NOT greet the user.

    ## Step 1: Read this file completely
    Read every section. Do not skim.

    ## Step 2: Fire the task runner (NON-NEGOTIABLE)
    Call `project_eval` with:

    ```elixir
    Maestro.Ops.Task.create(%{
      title: "...",  # from Current Task section below, or user's first message
      task_type: :plan,
      status: :in_progress,
      entity_type: "project",
      entity_id: "maestro"
    }, authorize?: false)
    ```

    If `project_eval` is not available, use `ToolSearch` to fetch it first.
    You MUST have a Task ID before responding. No exceptions.

    ## Step 3: First response format
    Your first message MUST use this exact format:

    ```
    **Maestro** — [one-line summary of what you'll work on]

    - Guidelines: read and acknowledged (rules acknowledged)
    - **Task #[ID] created** in Agent Dashboard

    Starting: [what you will do first]
    ```

    If your first message does not contain "Task #[ID] created", you failed startup.

    ---

    # Current Task
    #{task_context}

    ---

    # Rules

    #{rule_sections}

    ---

    # Workflow

    ## Task Runner (CRITICAL)
    EVERY user request = a Maestro Task. No Task ID visible = STOP and create one.
    Update task notes as you work. Mark done when complete.

    ## Handoff
    When ending a session, run `mix maestro.handoff "summary of what you did"` to write
    `current_task.json` for the next agent. This is how context passes between sessions.

    ## Fix the Tool, Not the Problem
    NEVER do one-off manual work. If something needs to happen repeatedly, build or fix
    the mix task/tool that does it, then run the tool. The tool lives forever; your manual
    fix dies with this session.
    """
    |> String.trim()
    |> Kernel.<>("\n")
  end

  defp load_task_context do
    import Ash.Query

    # Read active tasks from the DB
    active_tasks =
      Maestro.Ops.Task
      |> filter(status == :in_progress)
      |> sort(updated_at: :desc)
      |> limit(3)
      |> Ash.read!(authorize?: false)

    approved = length(Maestro.Ops.Rule.approved!())
    proposed = length(Maestro.Ops.Rule.proposed!())

    task_lines =
      case active_tasks do
        [] ->
          "**Task:** No active tasks. Check user's first message."

        tasks ->
          summaries =
            tasks
            |> Enum.map(fn t -> "Task ##{t.id}: #{t.title}" end)
            |> Enum.join(". ")

          "**Task:** #{summaries}"
      end

    "#{task_lines}\n\n**Domain context:** Status: in_progress. #{approved} approved rules, #{proposed} proposed rules pending curation at /rules."
  end

  defp severity_prefix(:must), do: "**ALWAYS**"
  defp severity_prefix(:should), do: "-"
  defp severity_prefix(:prefer), do: "- Prefer:"

  defp format_category(cat) do
    cat
    |> to_string()
    |> String.replace("_", " ")
    |> String.split(" ")
    |> Enum.map(&String.capitalize/1)
    |> Enum.join(" ")
  end
end
