defmodule Mix.Tasks.Maestro.Gen.Skills do
  @moduledoc """
  Generate Claude Code skill files from approved rules grouped by tag.

  Skills are .md files placed in ~/.claude/commands/ (user-level) that can be
  invoked as /skill-name in any project's Claude Code session.

  ## Usage

      # Preview what skills would be generated
      mix maestro.gen.skills

      # Generate skills to ~/.claude/commands/
      mix maestro.gen.skills --write

      # Generate to a specific directory
      mix maestro.gen.skills --write --output /path/to/dir
  """

  use Mix.Task
  @shortdoc "Generate Claude Code skills from approved rule clusters"

  @default_output Path.expand("~/.claude/commands")

  @spec run([String.t()]) :: :ok
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _, _} =
      OptionParser.parse(args,
        strict: [write: :boolean, output: :string]
      )

    write = opts[:write] || false
    output_dir = opts[:output] || @default_output

    rules = Maestro.Ops.Rule.approved!()

    # Group rules by tags to find skill clusters
    tag_groups =
      rules
      |> Enum.flat_map(fn rule ->
        Enum.map(rule.tags || [], fn tag -> {tag, rule} end)
      end)
      |> Enum.group_by(fn {tag, _} -> tag end, fn {_, rule} -> rule end)
      |> Enum.filter(fn {_tag, rules} -> length(rules) >= 2 end)
      |> Enum.sort_by(fn {_tag, rules} -> -length(rules) end)

    if tag_groups == [] do
      Mix.shell().info("No skill clusters found (need 2+ rules sharing a tag)")
      return_early()
    end

    Mix.shell().info("Found #{length(tag_groups)} skill clusters:\n")

    skills =
      Enum.map(tag_groups, fn {tag, tag_rules} ->
        skill_name = "maestro-#{tag}"
        content = render_skill(tag, tag_rules)

        Mix.shell().info("  /#{skill_name} — #{length(tag_rules)} rules")

        {skill_name, content}
      end)

    if write do
      File.mkdir_p!(output_dir)

      Enum.each(skills, fn {name, content} ->
        path = Path.join(output_dir, "#{name}.md")
        File.write!(path, content)
        Mix.shell().info("  Wrote #{path}")
      end)

      Mix.shell().info("\n#{length(skills)} skills generated in #{output_dir}")
    else
      Mix.shell().info("\nPass --write to generate skill files")
    end
  end

  defp render_skill(tag, rules) do
    rule_lines =
      rules
      |> Enum.sort_by(fn r -> severity_order(r.severity) end)
      |> Enum.map(fn rule ->
        severity = String.upcase(to_string(rule.severity))
        source = if rule.source_project_slug, do: " (from #{rule.source_project_slug})", else: ""
        "- [#{severity}] #{rule.content}#{source}"
      end)
      |> Enum.join("\n\n")

    """
    # #{String.capitalize(tag)} Rules

    Apply these rules when working on #{tag}-related code.
    Generated by Maestro from #{length(rules)} approved rules.
    Review at http://localhost:4004/rules

    #{rule_lines}
    """
    |> String.trim()
    |> Kernel.<>("\n")
  end

  defp severity_order(:must), do: 0
  defp severity_order(:should), do: 1
  defp severity_order(:prefer), do: 2

  defp return_early, do: :ok
end
