defmodule Mix.Tasks.Maestro.Map do
  @shortdoc "Generate MAP.md — codebase architecture index for agents"
  @moduledoc """
  Walks the codebase and produces a compact architecture index.

  Agents read MAP.md on startup instead of exploring files. It lists
  every module with its purpose, public functions, and relationships.

  ## Usage

      mix maestro.map              # Generate MAP.md
      mix maestro.map --dir lib    # Only index a subdirectory

  ## Output

  MAP.md contains:
  - Module name and file path
  - @moduledoc summary (first sentence)
  - Public function signatures
  - Grouped by domain (Maestro.Agents, Maestro.Ops, MaestroWeb, etc.)
  """

  use Mix.Task

  @impl true
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, strict: [dir: :string])
    dir = opts[:dir] || "lib"

    Mix.shell().info("Generating MAP.md from #{dir}/...")

    modules = walk_modules(dir)
    content = format_map(modules)

    File.write!("MAP.md", content)

    Mix.shell().info("Wrote MAP.md (#{length(modules)} modules)")
  end

  defp walk_modules(dir) do
    Path.wildcard("#{dir}/**/*.ex")
    |> Enum.reject(&String.contains?(&1, "/deps/"))
    |> Enum.map(&parse_module/1)
    |> Enum.reject(&is_nil/1)
    |> Enum.sort_by(& &1.module)
  end

  defp parse_module(path) do
    case File.read(path) do
      {:ok, source} ->
        module = extract_module_name(source)
        doc = extract_moduledoc_summary(source)
        functions = extract_public_functions(source)

        if module do
          %{
            module: module,
            path: path,
            doc: doc,
            functions: functions
          }
        end

      _ ->
        nil
    end
  end

  defp extract_module_name(source) do
    case Regex.run(~r/defmodule\s+([\w.]+)\s+do/, source) do
      [_, name] -> name
      _ -> nil
    end
  end

  defp extract_moduledoc_summary(source) do
    case Regex.run(~r/@moduledoc\s+"""\n\s*(.+?)(?:\n|\.\s)/, source) do
      [_, first_sentence] -> String.trim(first_sentence) |> String.slice(0, 120)
      _ -> nil
    end
  end

  defp extract_public_functions(source) do
    Regex.scan(~r/^\s+def\s+(\w+)\(([^)]*)\)/m, source)
    |> Enum.map(fn
      [_, name, args] ->
        arity = if args == "", do: 0, else: args |> String.split(",") |> length()
        "#{name}/#{arity}"
    end)
    |> Enum.uniq()
    |> Enum.reject(&String.starts_with?(&1, "handle_"))
    |> Enum.reject(&String.starts_with?(&1, "render/"))
    |> Enum.reject(&(&1 in ["mount/3", "mount/1", "update/2"]))
  end

  defp format_map(modules) do
    groups = group_modules(modules)
    date = Date.utc_today()

    header = """
    # Codebase Map
    # Generated by `mix maestro.map` · #{date} · #{length(modules)} modules
    #
    # Agents: read this on startup to understand the architecture.
    # Do NOT explore files manually — this index is authoritative.

    """

    body =
      groups
      |> Enum.sort_by(fn {group, _} -> group end)
      |> Enum.map(fn {group, mods} -> format_group(group, mods) end)
      |> Enum.join("\n")

    header <> body
  end

  defp group_modules(modules) do
    Enum.group_by(modules, fn m ->
      cond do
        String.starts_with?(m.module, "MaestroWeb.Live.") -> "LiveViews"
        String.starts_with?(m.module, "MaestroWeb.Components.") -> "Components"
        String.starts_with?(m.module, "MaestroWeb.") -> "Web"
        String.starts_with?(m.module, "Maestro.Agents.") -> "Agents"
        String.starts_with?(m.module, "Maestro.Ops.Rules.") -> "Rules Pipeline"
        String.starts_with?(m.module, "Maestro.Ops.") -> "Ops"
        String.starts_with?(m.module, "Mix.Tasks.Maestro.") -> "Mix Tasks"
        String.starts_with?(m.module, "Maestro.") -> "Core"
        true -> "Other"
      end
    end)
  end

  defp format_group(group, modules) do
    header = "## #{group}\n\n"

    entries =
      modules
      |> Enum.sort_by(& &1.module)
      |> Enum.map(&format_entry/1)
      |> Enum.join("\n")

    header <> entries <> "\n"
  end

  defp format_entry(mod) do
    doc_line = if mod.doc, do: " — #{mod.doc}", else: ""
    fn_line = if mod.functions != [], do: "\n  #{Enum.join(mod.functions, ", ")}", else: ""
    "- **#{mod.module}** `#{mod.path}`#{doc_line}#{fn_line}\n"
  end
end
