defmodule Mix.Tasks.Maestro.Rules.Export do
  @shortdoc "Export agent-readable rule bundles"
  @moduledoc """
  Generates compact, right-sized rule bundles for agent consumption.

  ## Usage

      mix maestro.rules.export              # Export all bundles
      mix maestro.rules.export --bundle ui  # Export a specific bundle
      mix maestro.rules.export --json       # Export as compact JSON
      mix maestro.rules.export --dir ./out  # Export to a specific directory

  ## Bundles

  - `universal` — Rules every agent must follow
  - `ui` — Rules for UI/frontend builders (LiveView, HEEx, CSS)
  - `model` — Rules for data model/backend builders (Ash, Elixir)
  - `devops` — Rules for deployment/ops tasks
  - `maestro` — Maestro-specific rules (not for other projects)

  Also regenerates `rules.json` as a compact universal bundle
  and updates `AGENTS.md` to reference the right bundle.
  """

  use Mix.Task

  alias Maestro.Ops.Rules.Bundler

  @impl true
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _, _} = OptionParser.parse(args,
      strict: [bundle: :string, json: :boolean, dir: :string],
      aliases: [b: :bundle, j: :json, d: :dir]
    )

    dir = opts[:dir] || "."
    json? = opts[:json] || false

    case opts[:bundle] do
      nil ->
        export_all(dir, json?)

      bundle ->
        bundle_atom = String.to_existing_atom(bundle)
        export_one(bundle_atom, dir, json?)
    end
  end

  defp export_all(dir, json?) do
    Mix.shell().info("Exporting all rule bundles...")

    # Generate markdown bundles
    files = Bundler.write_bundles(dir)
    Enum.each(files, &Mix.shell().info("  Wrote #{&1}"))

    # Always regenerate rules.json as compact universal
    json_content = Bundler.generate_compact_json(:universal)
    json_path = Path.join(dir, "rules.json")
    File.write!(json_path, json_content)

    rules_count = json_content |> Jason.decode!() |> length()
    json_size = byte_size(json_content)
    Mix.shell().info("  Wrote #{json_path} (#{rules_count} rules, #{div(json_size, 1024)}KB)")

    if json? do
      export_json_bundles(dir)
    end

    # Update AGENTS.md
    update_agents_md(dir)

    # Update RULES.md as combined reference
    update_rules_md(dir)

    Mix.shell().info("Done! #{length(files) + 1} files exported.")
  end

  defp export_one(bundle, dir, json?) do
    if json? do
      content = Bundler.generate_compact_json(bundle)
      path = Path.join(dir, "rules.#{bundle}.json")
      File.write!(path, content)
      rules_count = content |> Jason.decode!() |> length()
      Mix.shell().info("Wrote #{path} (#{rules_count} rules)")
    else
      content = Bundler.generate_bundle(bundle)
      path = Path.join(dir, "rules.#{bundle}.md")
      File.write!(path, content)
      lines = content |> String.split("\n") |> length()
      Mix.shell().info("Wrote #{path} (#{lines} lines)")
    end
  end

  defp export_json_bundles(dir) do
    for bundle <- [:ui, :model, :devops] do
      content = Bundler.generate_compact_json(bundle)
      path = Path.join(dir, "rules.#{bundle}.json")
      File.write!(path, content)
      rules_count = content |> Jason.decode!() |> length()
      Mix.shell().info("  Wrote #{path} (#{rules_count} rules)")
    end
  end

  defp update_agents_md(dir) do
    agents_md = """
    # Agent Rules

    1. Read and follow ALL rules in `rules.json`.
       confirm:
         You have read rules.json (state the count)
         You will follow the rules

    2. Read `current_task.json` for your current task and context from the previous session.
       confirm:
         You have read current_task.json (summarize the current state and what's next)
    """

    path = Path.join(dir, "AGENTS.md")
    File.write!(path, agents_md)
    Mix.shell().info("  Wrote #{path}")
  end

  defp update_rules_md(dir) do
    bundles = Bundler.generate_all()

    total_rules =
      bundles
      |> Map.values()
      |> Enum.map(fn content ->
        lines = String.split(content, "\n")
        Enum.count(lines, &String.starts_with?(&1, "MUST:")) +
        Enum.count(lines, &String.starts_with?(&1, "SHOULD:")) +
        Enum.count(lines, &String.starts_with?(&1, "PREFER:"))
      end)
      |> Enum.sum()

    header = """
    # Rules
    # Generated by `mix maestro.rules.export` · #{Date.utc_today()} · #{total_rules} rules across #{map_size(bundles)} bundles
    #
    # Agents read `rules.json` (universal) and optionally a specialized bundle.
    # This file is a combined reference of all bundles.
    """

    body =
      bundles
      |> Enum.sort_by(fn {name, _} -> to_string(name) end)
      |> Enum.map(fn {_name, content} -> content end)
      |> Enum.join("\n---\n\n")

    path = Path.join(dir, "RULES.md")
    File.write!(path, header <> "\n" <> body)
    Mix.shell().info("  Wrote #{path}")
  end
end
