defmodule Maestro.Repo.Migrations.AddEditorCommandToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :editor_command, :text, default: "code"
    end
  end

  def down do
    alter table(:users) do
      remove :editor_command
    end
  end
end
