defmodule Maestro.Repo.Migrations.AddCompletedAtToTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :completed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:tasks) do
      remove :completed_at
    end
  end
end
