defmodule Maestro.Repo.Migrations.CreateProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :web_port, :bigint, null: false
      add :debugger_port, :bigint
      add :github_url, :text
      add :status, :text, default: "unknown"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    create unique_index(:projects, [:web_port], name: "projects_unique_web_port_index")
  end

  def down do
    drop_if_exists unique_index(:projects, [:web_port], name: "projects_unique_web_port_index")

    drop_if_exists unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    drop table(:projects)
  end
end
