defmodule Maestro.Repo.Migrations.AddPriorityAndBundleToRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rules) do
      add :priority, :bigint, default: 50
      add :bundle, :text, default: "universal"
    end
  end

  def down do
    alter table(:rules) do
      remove :bundle
      remove :priority
    end
  end
end
