defmodule Maestro.Repo.Migrations.AddLibrariesRuleSourcesSkills do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:skills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :skill_path, :text
      add :managed_by, :text
      add :library_names, {:array, :text}, default: []
      add :reference_files, {:array, :text}, default: []
      add :last_synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:skills, [:name], name: "skills_unique_name_index")

    alter table(:rules) do
      add :content_hash, :text
      add :library_id, :uuid
      add :rule_source_id, :uuid
    end

    create table(:rule_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :file_path, :text, null: false
      add :sub_rule_name, :text
      add :content_hash, :text
      add :rule_count, :bigint, default: 0
      add :last_synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :library_id, :uuid, null: false
    end

    create table(:libraries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:rules) do
      modify :library_id,
             references(:libraries,
               column: :id,
               name: "rules_library_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :rule_source_id,
             references(:rule_sources,
               column: :id,
               name: "rules_rule_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:rule_sources) do
      modify :library_id,
             references(:libraries,
               column: :id,
               name: "rule_sources_library_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:rule_sources, [:library_id, :file_path],
             name: "rule_sources_unique_path_index"
           )

    alter table(:libraries) do
      add :name, :text, null: false
      add :version, :text
      add :description, :text
      add :last_synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:libraries, [:name], name: "libraries_unique_name_index")

    # Backfill content_hash on existing rules
    execute """
    UPDATE rules
    SET content_hash = encode(
      sha256(lower(regexp_replace(trim(content), '\\s+', ' ', 'g'))::bytea),
      'hex'
    )
    WHERE content_hash IS NULL
    """
  end

  def down do
    drop_if_exists unique_index(:libraries, [:name], name: "libraries_unique_name_index")

    alter table(:libraries) do
      remove :updated_at
      remove :inserted_at
      remove :last_synced_at
      remove :description
      remove :version
      remove :name
    end

    drop_if_exists unique_index(:rule_sources, [:library_id, :file_path],
                     name: "rule_sources_unique_path_index"
                   )

    drop constraint(:rule_sources, "rule_sources_library_id_fkey")

    alter table(:rule_sources) do
      modify :library_id, :uuid
    end

    drop constraint(:rules, "rules_library_id_fkey")

    drop constraint(:rules, "rules_rule_source_id_fkey")

    alter table(:rules) do
      modify :rule_source_id, :uuid
      modify :library_id, :uuid
    end

    drop table(:libraries)

    drop table(:rule_sources)

    alter table(:rules) do
      remove :rule_source_id
      remove :library_id
      remove :content_hash
    end

    drop_if_exists unique_index(:skills, [:name], name: "skills_unique_name_index")

    drop table(:skills)
  end
end
