defmodule Maestro.Repo.Migrations.AddRuleDirective do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rules) do
      add :directive, :text
    end

    # Infer only from explicit leading language. A mention of "never" later in
    # explanatory prose must not reverse the instruction that leads the rule.
    execute """
    UPDATE rules
    SET directive = CASE
      WHEN content ~* '^[[:space:]]*(-[[:space:]]*)?(\\*\\*)?[[:space:]]*(never|avoid|must[[:space:]]+not|should[[:space:]]+not|do[[:space:]]+not|don''t|you[[:space:]]+are[[:space:]]+forbidden|forbidden)(\\*\\*)?([[:space:]]*:|[[:space:]])'
        THEN 'forbid'
      WHEN content ~* '^[[:space:]]*(-[[:space:]]*)?(\\*\\*)?[[:space:]]*prefer(\\*\\*)?([[:space:]]*:|[[:space:]])'
        THEN 'prefer'
      ELSE 'require'
    END
    WHERE directive IS NULL
    """

    alter table(:rules) do
      modify :directive, :text, null: false
    end
  end

  def down do
    alter table(:rules) do
      remove :directive
    end
  end
end
