defmodule Maestro.Repo.Migrations.AddSupersededByToRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rules) do
      add :superseded_by_id,
          references(:rules,
            column: :id,
            name: "rules_superseded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:rules, "rules_superseded_by_id_fkey")

    alter table(:rules) do
      remove :superseded_by_id
    end
  end
end
