defmodule Maestro.Repo.Migrations.AddSwimEventsAndSourceFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:swim_source_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :path, :text
      add :format, :text, null: false
      add :record_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :meet_id,
          references(:swim_meets,
            column: :id,
            name: "swim_source_files_meet_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:swim_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :number, :bigint, null: false
      add :distance, :bigint, null: false
      add :stroke, :text, null: false
      add :gender, :text
      add :event_type, :text
      add :category, :text
      add :category_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :meet_id,
          references(:swim_meets,
            column: :id,
            name: "swim_events_meet_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:swim_events, "swim_events_meet_id_fkey")

    drop table(:swim_events)

    drop constraint(:swim_source_files, "swim_source_files_meet_id_fkey")

    drop table(:swim_source_files)
  end
end
