defmodule Maestro.Repo.Migrations.AddSourceTypeToRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rules) do
      add :source_type, :text, default: "manual"

      add :source_agent_session_id,
          references(:ops_agent_sessions,
            column: :id,
            name: "rules_source_agent_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # Backfill source_type from existing data
    execute "UPDATE rules SET source_type = 'library_file' WHERE rule_source_id IS NOT NULL"
    execute "UPDATE rules SET source_type = 'consolidated' WHERE source_context LIKE 'consolidated:%'"
    execute "UPDATE rules SET source_type = 'article' WHERE source_context LIKE 'Extracted from http%'"
  end

  def down do
    drop constraint(:rules, "rules_source_agent_session_id_fkey")

    alter table(:rules) do
      remove :source_agent_session_id
      remove :source_type
    end
  end
end
