defmodule Maestro.Repo.Migrations.DropUniqueWebPortIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:projects, [:web_port], name: "projects_unique_web_port_index")
  end

  def down do
    create unique_index(:projects, [:web_port], name: "projects_unique_web_port_index")
  end
end
