defmodule Maestro.Repo.Migrations.AddProjectToAudits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audits) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "audits_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:audits, "audits_project_id_fkey")

    alter table(:audits) do
      remove :project_id
    end
  end
end
