defmodule Maestro.Repo.Migrations.AddEmbeddedConfigsToRule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rules) do
      add :lint_config, :map
      add :fix_config, :map
    end
  end

  def down do
    alter table(:rules) do
      remove :fix_config
      remove :lint_config
    end
  end
end
