defmodule Maestro.Repo.Migrations.AddNotesToAudits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audits) do
      add :notes, :text
    end
  end

  def down do
    alter table(:audits) do
      remove :notes
    end
  end
end
