defmodule Maestro.Repo.Migrations.CreateRulesResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :category, :text, null: false
      add :severity, :text, default: "should"
      add :status, :text, default: "proposed"
      add :source_project_slug, :text
      add :source_commit, :text
      add :source_context, :text
      add :applies_to, {:array, :text}, default: fragment("'{all}'::text[]")
      add :tags, {:array, :text}, default: []
      add :retired_reason, :text
      add :approved_at, :utc_datetime_usec
      add :retired_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:rules)
  end
end
