defmodule Maestro.Repo.Migrations.SyncAgentSessionsSnapshot do
  @moduledoc """
  No-op: agent_sessions table already exists. This migration only creates the Ash snapshot.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up, do: :ok
  def down, do: :ok
end
