defmodule Maestro.Repo.Migrations.AddFixFieldsToRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Columns already added by manual migration 20260322135525
  end

  def down do
  end
end
