defmodule Maestro.Repo.Migrations.CreateSwimDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:swim_swimmers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :last_name, :text, null: false
      add :first_name, :text, null: false
      add :usa_swimming_id, :text
      add :dob, :date
      add :gender, :text
      add :team_code, :text
      add :age, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:swim_meets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :location, :text
      add :host_team, :text
      add :meet_date, :date
      add :course, :text, default: "Y"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:swim_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_number, :bigint, null: false
      add :event_name, :text
      add :seed_time, :text
      add :seed_time_seconds, :float
      add :course, :text, default: "Y"
      add :stroke, :text
      add :distance, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :meet_id,
          references(:swim_meets,
            column: :id,
            name: "swim_entries_meet_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :swimmer_id,
          references(:swim_swimmers,
            column: :id,
            name: "swim_entries_swimmer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:swim_entries, "swim_entries_meet_id_fkey")

    drop constraint(:swim_entries, "swim_entries_swimmer_id_fkey")

    drop table(:swim_entries)

    drop table(:swim_meets)

    drop table(:swim_swimmers)
  end
end
