defmodule Maestro.Repo.Migrations.SetRuleAppliesToDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rules) do
      modify :applies_to, {:array, :text}, default: fragment("'{all}'::text[]")
    end
  end

  def down do
    alter table(:rules) do
      modify :applies_to, {:array, :text}, default: nil
    end
  end
end
