defmodule Maestro.Repo.Migrations.CreateAgentsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false
      add :model, :text
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:agent_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :task_description, :text
      add :status, :text, default: "active"
      add :metadata, :map, default: %{}
      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_sessions_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:agent_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :content, :text, null: false
      add :response, :text
      add :metadata, :map, default: %{}
      add :response_metadata, :map, default: %{}
      add :duration_ms, :bigint
      add :responded_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_requests_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_id,
          references(:agent_sessions,
            column: :id,
            name: "agent_requests_session_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:agent_requests, "agent_requests_agent_id_fkey")

    drop constraint(:agent_requests, "agent_requests_session_id_fkey")

    drop table(:agent_requests)

    drop constraint(:agent_sessions, "agent_sessions_agent_id_fkey")

    drop table(:agent_sessions)

    drop table(:agents)
  end
end
