defmodule Maestro.Repo.Migrations.AuditResourcesFix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audits, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :status, :text, null: false, default: "running"
      add :total_pages, :bigint, default: 0
      add :avg_score, :bigint, default: 0
      add :total_checks, :bigint, default: 0
      add :total_pass, :bigint, default: 0
      add :total_fail, :bigint, default: 0
      add :rules_checked, :bigint, default: 0
      add :rules_skipped_per_page, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:audit_results, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :path, :text, null: false
      add :module_name, :text, null: false
      add :source_file, :text
      add :score, :bigint, default: 100
      add :pass, :bigint, default: 0
      add :fail, :bigint, default: 0
      add :skip, :bigint, default: 0
      add :total, :bigint, default: 0
      add :findings, {:array, :map}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :audit_id,
          references(:audits,
            column: :id,
            name: "audit_results_audit_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:audit_results, "audit_results_audit_id_fkey")

    drop table(:audit_results)

    drop table(:audits)
  end
end
