defmodule Maestro.Repo.Migrations.AddProdUrlToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :prod_url, :text
    end
  end

  def down do
    alter table(:projects) do
      remove :prod_url
    end
  end
end
